# Generated by Django 4.2.23 on 2025-08-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=255)),
                ('channel_title', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('comments_analyzed', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=255, unique=True)),
                ('video_id', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('author_channel_url', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=50)),
                ('toxicity_score', models.FloatField(blank=True, null=True)),
                ('toxicity_label', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('key_topics', models.JSONField(blank=True, default=list)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['video_id'], name='api_comment_video_i_3b44da_idx'), models.Index(fields=['sentiment_label'], name='api_comment_sentime_f16ae0_idx'), models.Index(fields=['toxicity_label'], name='api_comment_toxicit_c184a8_idx'), models.Index(fields=['published_at'], name='api_comment_publish_248288_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total_comments', models.IntegerField(default=0)),
                ('analyzed_comments', models.IntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
