# Generated by Django 4.2.23 on 2025-08-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_available',
            field=models.BooleanField(default=False),
        ),
    ]
