# Generated by Django 4.2.23 on 2025-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_video_transcript_video_transcript_analyzed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript_analyzed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript_available',
        ),
    ]
