# Generated by Django 4.2.7 on 2025-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
